apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/<your-user>/<repo>
    path: helm-charts/backend
    targetRevision: HEAD
    helm:
      valueFiles:
        - environments/dev/values-backend.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true